### ISSUE TITLE
Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by skischuh** [tepez/protractor-video-reporter#1]
Hi,
when i try the protractor-video-reporter without specified `ffmpegArgs`, i get the following error:
```
Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

when i try it with the following default `ffmpegArgs`:
```
            ffmpegArgs: [
                '-y',
                '-r',
                '30',
                '-f',
                'x11grab',
                '-s',
                '1024x768',
                '-i',
                process.env.DISPLAY,
                '-g',
                '300',
                '-vcodec',
                'qtrle',
            ],
```
I get the following error:
```
[launcher] Error: ValidationError: child "ffmpegArgs" fails because ["ffmpegArgs" must not be a sparse array]
    at Object.exports.process (D:\......\node_modules\protractor-video-reporter\node_modules\joi\lib\errors.js:140:17)
```

Can you provide any help or code examples?

Thanks

**Comment by tepez** [comment]
1. It seems you don't have ffmpeg installed.
2. It seems `process.env.DISPLAY` is undefined.

**Comment by skischuh** [comment]
Thanks for your response! I'll check this out.

Btw, does this reporter work on Windows?

**Comment by tepez** [comment]
I only tried it on Ubuntu.
I guess you could run it on Windows if you configure ffmpeg correctly.
It's currently configured to use Xvfb.

See:
https://trac.ffmpeg.org/wiki/Capture/Desktop#Windows

**Comment by skischuh** [comment]
Thanks again. It finally worked for me on Windows with the following code:
```
    onPrepare: function () {
        var VideoReporter = require('protractor-video-reporter');
        jasmine.getEnv().addReporter(new VideoReporter({
            baseDirectory: 'D:\\videos\\',
            saveSuccessVideos: true,
            ffmpegCmd: "C:\\FFmpeg\\bin\\ffmpeg.exe",
            ffmpegArgs: [
                '-f',
                'gdigrab',
                '-framerate',
                '30',
                '-i',
                'title=Google - Mozilla Firefox'
            ],
            debug: true
        }));
```
`gdigrab` was a good alternative to Linux' `x11grab`, so I didn't actually need something like `screen-capture-recorder` or `UScreenCapture`. Then I also had to overwrite the file extension in `defaultVideoPath` in `VideoReporter.js`:
```
function defaultVideoPath(result) {
	return Uuid.v4() + '.mpg'; //return Uuid.v4() + '.mov';
}
```
The last problem was that Windows Media Player couldn't read the videos. So I installed VLC Player and everything was fine.

**Comment by tepez** [comment]
Great. Happy to hear it worked for you.

**Comment by Avanish023** [comment]
@skischuh  can you give me an example of how you did it on windows,
Here i am not getting any video file but i am getting srt file with your code.

**Comment by skischuh** [comment]
@Avanish023 

Meahwhile our code in the config file looks as follows:

```
onPrepare: function () {
        ...
        global.screenVideo = function (browserName) {
            var VideoReporter = require('protractor-video-reporter');
            jasmine.getEnv().addReporter(new VideoReporter({
                baseDirectory: 'D:\\selenium_screen_videos\\',
                saveSuccessVideos: false,
                ffmpegCmd: "C:\\FFmpeg\\bin\\ffmpeg.exe",
                ffmpegArgs: [
                    '-f',
                    'dshow',
                    '-i',
                    'video=screen-capture-recorder'
                ],
                debug: false
            }));
        };
        ...
        var SpecReporter = require('jasmine-spec-reporter');
        // add jasmine spec reporter
        jasmine.getEnv().addReporter(new SpecReporter());

        var jasmineReporters = require('jasmine-reporters');

        return browser.getProcessedConfig().then(function (config) {
            // you could use other properties here if you want, such as platform
            // and version
            var browserName = config.capabilities.browserName;
            var junitReporter = new jasmineReporters.JUnitXmlReporter({
                consolidateAll: false,
                savePath: 'testReports/' + browserName,
                // this will produce distinct xml files for each capability
                filePrefix: 'xmloutput-',
                modifySuiteName: function (generatedSuiteName, suite) {
                    // this will produce distinct suite names for each
                    // capability,
                    // e.g. 'firefox.login tests' and 'chrome.login tests'
                    return browserName + '.' + generatedSuiteName;
                }
            });
            screenVideo(browserName.replace(' ', '_'));
            jasmine.getEnv().addReporter(junitReporter);
        });
        browser.ignoreSynchronization = false;
        ...
},
...
```

I don't know any details though as I haven't been working on this for a while.

**Comment by Avanish023** [comment]
@skischuh 
Thanks for reply ,

if you remember I have couple of questions please do answer ,

Did you do anything with xvfb or node-gyp for getting video.?
Something like installing python,
my code does not give me any error but it does not generate `videos too


Below is my code
 
    onPrepare: function () {
        var browserName, browserVersion;
        var capsPromise = browser.getCapabilities();
 
        capsPromise.then(function (caps) {
        browserName = caps.get('browserName');
        browserVersion = caps.get('version');
        });
        
        
        global.screenVideo = function (browserName) {
        var VideoReporter = require('protractor-video-reporter');
        jasmine.getEnv().addReporter(new VideoReporter({
            baseDirectory: './videos/',
            saveSuccessVideos: true,
            ffmpegCmd: "C:\\ffmpeg\\bin\\ffmpeg.exe",
            ffmpegArgs: [
                    '-f',
                    'dshow',
                    '-i',
                    'video=screen-capture-recorder'
                ],
           
        }));
        };
        
        screenVideo(browserName);

![image](https://user-images.githubusercontent.com/28143223/28201746-0b8c8c04-6890-11e7-82c9-d9e870203cef.png)

It says it has generated video 
![image](https://user-images.githubusercontent.com/28143223/28201767-23b22316-6890-11e7-8d34-2a0b90d9114a.png)
But it is has not.

Any help would be much appreciated .

        `
