### ISSUE TITLE
Include beforeAll and beforeEach in Video Capturing

### ISSUE THREAD

**Issue by skischuh** [tepez/protractor-video-reporter#3]
I would like to video capture all `it` test cases including the commands in `beforeAll` and `beforeEach`.

How can I do that?

**Comment by tepez** [comment]
It should be captured. Are you sure it's not?

Capturing is started by [specStarted](http://jasmine.github.io/2.1/custom_reporter.html#section-specStarted), and:

> specStarted is invoked when an it starts to run (including associated beforeEach functions)

**Comment by skischuh** [comment]
Oh, it captures the commands in `beforeEach` but not those in `beforeAll`. So thats fine, thank you.
