### ISSUE TITLE
option defaults

### ISSUE THREAD

**Issue by vlio20** [tepez/protractor-video-reporter#5]
Hey,
It would be nice if you will add the defaults for the configuration options.

**Comment by tepez** [comment]
I've just updated the docs and published version 0.2.
Are the docs clear now?

**Comment by vlio20** [comment]
Yes, thanks.
Maybe you can point me to a good source on how to install the Xvfb locally on local mac machine.
I will close this issue

**Comment by tepez** [comment]
This is my recipe for Ubuntu. Maybe it'll help you:

### Install Xvfb

    sudo apt-get install xvfb chromium-browser

##### In one terminal:

    sudo Xvfb :1

##### In another teminal:

    export DISPLAY=:1
    export CHROME_BIN=/usr/bin/chromium-browser
    webdriver-manager start

##### In another teminal:

    protractor

**Comment by vlio20** [comment]
Thanks, but the apt-get made for linux machines. In mac I can use brew but seems that there is no xvfb module there.

**Comment by benc** [comment]
`xvfb` is something X11 specific - AFAIK there is no equivalent for mac
